// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.springframework.roo.petclinic.web;

import io.springlets.boot.test.autoconfigure.web.servlet.SpringletsWebMvcTest;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.roo.petclinic.domain.dod.VisitFactory;
import org.springframework.roo.petclinic.service.api.VisitService;
import org.springframework.roo.petclinic.web.VisitsItemThymeleafController;
import org.springframework.roo.petclinic.web.VisitsItemThymeleafControllerIT;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.test.web.servlet.MockMvc;

privileged aspect VisitsItemThymeleafControllerIT_Roo_ThymeleafControllerIntegrationTest {
    
    declare @type: VisitsItemThymeleafControllerIT: @RunWith(SpringRunner.class);
    
    declare @type: VisitsItemThymeleafControllerIT: @SpringletsWebMvcTest(controllers = VisitsItemThymeleafController.class, secure = false);
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @Autowired
    public MockMvc VisitsItemThymeleafControllerIT.mvc;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @MockBean
    public VisitService VisitsItemThymeleafControllerIT.visitServiceService;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public VisitFactory VisitsItemThymeleafControllerIT.factory = new VisitFactory();
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return MockMvc
     */
    public MockMvc VisitsItemThymeleafControllerIT.getMvc() {
        return mvc;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return VisitService
     */
    public VisitService VisitsItemThymeleafControllerIT.getVisitServiceService() {
        return visitServiceService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return VisitFactory
     */
    public VisitFactory VisitsItemThymeleafControllerIT.getFactory() {
        return factory;
    }
    
    /**
     * Test method example. To be implemented by developer.
     * 
     */
    @Test
    public void VisitsItemThymeleafControllerIT.testMethodExample() {
        // Setup
        // Previous tasks
        
        // Exercise
        // Execute method to test
        
        // Verify
        // Check results with assertions
    }
    
}
