// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.disid.restful.model;

import com.disid.restful.model.AddressTest;
import com.disid.restful.model.dod.AddressFactory;

privileged aspect AddressTest_Roo_JpaUnitTest {
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private AddressFactory AddressTest.addressFactory = new AddressFactory();
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return AddressFactory
     */
    public AddressFactory AddressTest.getAddressFactory() {
        return addressFactory;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param addressFactory
     */
    public void AddressTest.setAddressFactory(AddressFactory addressFactory) {
        this.addressFactory = addressFactory;
    }
    
}
